version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
